#!/bin/bash
echo "🔥 CLAUDE SESSION RESTART DETECTED 🔥"
echo ""
echo "📋 Tell Claude to read memory documents:"
echo "   'Read your memory documents and continue'"
echo ""
echo "📁 Memory files available:"
echo "   - CLAUDE_UNIVERSAL_PROTOCOL.md"
echo "   - SESSION_MANAGEMENT_PROTOCOL.md" 
echo "   - CLAUDE_MEMORY.md"
echo "   - STRATEGIC_MASTER_PLAN.md"
echo ""
echo "🎯 Current Phase: Phase 1 - Deployment"
echo "🚀 Next Action: Deploy Next.js from GitHub to Vercel"
echo ""